### ISSUE TITLE
Cant connect to svn server?

### ISSUE THREAD

**Issue by lipe123** [MarkusH1975/svnserver.svn.mh#5]
I've never felt this dumb in my life.
I'm new to docker and never used it before but I need to get on DSM 7 and decided to use this container to migrate my SVN server.

I got the container installed and running, I have mapped my existing repo folder to the /volume/svnrepo/ folder and I can see it in the docker terminal.
When I do svnadmin <reponame> I get the stats for it.
I got the moinitorix url working, so I know its up and responding to network connections.

I installed tortoise svn on another computer, tried to open svn://servername "unable to connect, couldn't find a repository"
Can't seen to get the connection to the svn server to work at all.

**Comment by lipe123** [comment]
Ok I have updates, If I edit svnserver.conf  and set:anon-access =read
I can now see the projects, I can't seen to get auth working.
Can you please point me in the direction to help there? 
The passwd file is in the same folder and has a user and password in it but when I use tortoise svn for example I get a prompt for a root login first?!

**Comment by LingDan** [comment]
I've nearly the same problem. "svnserve.conf" and passwd copied from existing Synology SVN repo:


[general]
anon-access = none
auth-access = write

When I try to checkout or browse with repo browser (using TortoiseSVN) I got "Unable to connect to a repository at URL 'svn://myurl/foo' Authentication error from server: Internal server error in authentication".

I added logging to /var/log/svnserve.log to svnserve command in entrypoint script to get more details:

2023-01-05T00:07:44.295919Z 172.29.0.1 - - ERR - 0 210005 No repository found in 'svn://myurl'
2023-01-05T00:07:44.587628Z 172.29.0.1 - - ERR - 0 210002 Network connection closed unexpectedly
2023-01-05T00:07:44.806980Z 172.29.0.1 - - ERR - 0 210002 Network connection closed unexpectedly

I don't know where the issue could be. Also tried to make the file access more secure and only give root permission to passwd and svnserve.conf, but nothing changed.

If I set "anon-access = read" I am able to browse files with TortoiseSVN, so the repo is reachable and accessible.

Im running this under latest DSM 6 version (DSM 6.2.4-25556 Update 6) to be prepared before updating to DSM 7.

Would be nice to get some help, because I really like this simple solution ... once I get it fully working.

**Comment by lipe123** [comment]
I ultimately gave up and used a different docker option and it just worked right from the start.

**Comment by Rico-E** [comment]
@lipe123 could you explain what you did. I've spent 4hours on this problem, so it'd be nice if you could help.

**Comment by MarkusH1975** [comment]
See updated ACL:
https://github.com/MarkusH1975/svnserver.svn.mh#svn-access-control

**Comment by GTMany** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
